apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: us.gcr.io/ehole-k8s/webapp:2
          command: ["ruby", "app/app.rb"]
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /app
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
          ports:
          - containerPort: 8080
            name: http
          env:
            - name: REDIS_HOST
              value: 'redis-master'
            - name: REDIS_PORT
              value: '6379'
              - name: SECRET1
                valueFrom:
                  secretKeyRef: very-secret
                  key: val1
              - name: SECRET2
                valueFrom:
                  secretKeyRef: very-secret
                  key: val2
          resources:
            limits:
              cpu: 200m
              memory: 300Mi
            requests:
              cpu: 200m
              memory: 300Mi
